export enum TimeOffRequestStatus {
  PENDING_MANAGER_APPROVAL = 'PENDING_MANAGER_APPROVAL',
  APPROVED_SYNCED = 'APPROVED_SYNCED',
  APPROVED_SYNC_PENDING = 'APPROVED_SYNC_PENDING',
  REJECTED = 'REJECTED',
  CANCELLED = 'CANCELLED',
}

export const RESERVING_STATUSES: TimeOffRequestStatus[] = [
  TimeOffRequestStatus.PENDING_MANAGER_APPROVAL,
  TimeOffRequestStatus.APPROVED_SYNC_PENDING,
];
